### ISSUE TITLE
Allow user to add more buttons using json file

### ISSUE THREAD

**Issue by WesleyVong** [fredvong/syn_ui#1]

**Comment by fredvong** [comment]
{
  "name": "Wesley's synthesizer",
  "device": "/dev/tty.usbmodem208A366847521",
  "button_config": {
    "start_value": "0x3c",
    "labels": [
      "key00",
      "key01",
      "key02",
      "key03",
      "key04",
      "key05",
      "key06",
      "key07",
      "key08",
      "key09",
      "key10",
      "key11"
    ]
  },

Have you tried to add more labels?

**Comment by WesleyVong** [comment]
Sorry, the issue is not with the buttons, but with the knobs.

**Comment by fredvong** [comment]
"knob_config": {
    "labels": [
      "knob00",
      "knob01",
      "knob02",
      "knob03",
      "knob10",
      "knob11",
      "knob12",
      "knob13",
      "knob20",
      "knob21",
      "knob22",
      "knob23",
      "knob30",
      "knob31",
      "knob32",
      "knob33",
      "knob40",
      "knob41",
      "knob42",
      "knob43",
      "knob50",
      "knob51",
      "knob52",
      "knob53"
    ]

Have your tried to add more knobs in the label?

**Comment by fredvong** [comment]
You may need to restart the program to take the effects.

**Comment by WesleyVong** [comment]
Restarting the program fixes the issue.
